
vocabolary:
    pages: Pages
    title: Title
    last_edit: Last edit
    save: Save
    language: Language

pages:
    failed_permission: You don't have permission to do this action
    failed_update: Page is not updated because of an error
    success_update: Page is updated
